Add fortran to mac build

diff --git a/.github/workflows/build-mac.yml b/.github/workflows/build-mac.yml
--- a/.github/workflows/build-mac.yml
+++ b/.github/workflows/build-mac.yml
@@ -39,6 +39,18 @@ jobs:
           brew install gcc
           GFORTRAN_PATH=$(brew --prefix)/bin/gfortran
           echo "GFORTRAN_PATH=$GFORTRAN_PATH"
+          if [ -x "$GFORTRAN_PATH" ]; then
+            sudo ln -s $GFORTRAN_PATH /usr/local/bin/gfortran || true
+            sudo ln -s $GFORTRAN_PATH /usr/local/bin/f90 || true
+            sudo ln -s $GFORTRAN_PATH /usr/local/bin/f77 || true
+            sudo ln -s $GFORTRAN_PATH /usr/local/bin/f95 || true
+            echo "Adding $GFORTRAN_PATH to PATH"
+            echo "$GFORTRAN_PATH" >> $GITHUB_PATH
+          else
+            echo "gfortran not found"
+            exit 1
+          fi
+          gfortran --version
       - name: Compile and run Fortran code
         run: |
           ./setup_fortran.sh
